#!/usr/bin/env python3

from PIL import Image
from sys import argv
import os.path

start = int(argv[1])
end = int(argv[2])

for i in range(start, end):
    if i <= 0 and i + 1 < end:
        i += 1
    if i < 10:
        if os.path.exists('00' + str(i) + '.jpg'):
            img = Image.open('00' + str(i) + '.jpg').convert('L')
            img.save('00' + str(i) + '.jpg')
        elif os.path.exists('00' + str(i) + '.png'):
            img = Image.open('00' + str(i) + '.png').convert('L')
            img.save('00' + str(i) + '.png')
    elif i < 100:
        if os.path.exists('0' + str(i) + '.jpg'):
            img = Image.open('0' + str(i) + '.jpg').convert('L')
            img.save('0' + str(i) + '.jpg')
        elif os.path.exists('0' + str(i) + '.png'):
            img = Image.open('0' + str(i) + '.png').convert('L')
            img.save('0' + str(i) + '.png')
    else:
        if os.path.exists(str(i) + '.jpg'):
            img = Image.open(str(i) + '.jpg').convert('L')
            img.save(str(i) + '.jpg')
        elif os.path.exists(str(i) + '.png'):
            img = Image.open(str(i) + '.png').convert('L')
            img.save(str(i) + '.png')
