.TH manga-dl2 "1" "16 March 2018" "User info" "User info"
.SH NAME
manga-dl2 \- Manga's downloader
.SH SYNOPSIS
.B manga-dl2
.TP
.SH DESCRIPTION
.PP
MANGA-DL download some mangas from japscan, scan-vf or other sources.
.TP
.SH TESTED COMPATIBILITIES
.PP
Fedora 27, Archlinux
.TP
\fB-h, --help\fR
To see how it's work. (ง•̀_•́)ง
.TP
\fBRequired\fR
fiew things in site's URL, see the --help.
.TP
.PP
.SH AUTHORS
.B Created by 41M3
