.TH MOTTI_Aimé "1" "8 November 1999" "User info" "User info"
.SH NAME
Mon Man \- Pour les controler tous !!! 
.SH SYNOPSIS
.B man motti [options]
.TP
.SH DESCRIPTION
.PP
Once upon a time on a little ... Ouai bref une belle histoire d'un truc qui pourrait servir s'il avait une utilité utile !
Tu veux des détails ? Et bah \(aqMan google\(aq mon petit.
.TP
\fB-o, --comme ours ?\fR
peut-être un truc ... \(aqMAYBE\(aq
.TP
\fB-h, --help\fR
Une aide que tu peux trouver sur l'internet blaireau !
.TP
.PP
.SH AUTHORS
.B Created by Aimé Motti and nobody else
